name: Build source rpm
description: Build source rpm
inputs:
  tarball:
    description: Tarball with the sources
    required: true
  specfile:
    description: RPM spec file
    required: true
  sourcefiles:
    description: Additional source files
    required: false
outputs:
  path:
    description: Path to the created source rpm
  file:
    description: File name to the created source rpm
runs:
  using: 'docker'
  image: 'container/Dockerfile'
  args:
  - ${{ inputs.tarball }}
  - ${{ inputs.specfile }}
  - ${{ inputs.sourcefiles }}
